#!/usr/bin/env node
//
// SOTD-comparison artifact for each ship.
//
// Fires in Phase 6 (after the screenshot capture). Fetches the
// awwwards.com Site of the Day index, picks the top entry, and writes
// a 3-bullet "they vs us" delta to:
//
//   .claude/improvement/sotd/<commit-sha>.md
//
// The routine reads this back into the IMPROVEMENTS.md entry under a
// **SOTD comparison** section.
//
// Constraints:
//   - This script DOES NOT use an LLM. It only scrapes the gallery
//     page for the SOTD's name + URL + headline blurb, then writes a
//     skeleton markdown file. The routine's main agent can read this
//     skeleton and elaborate the 3 bullets if it wants — but the
//     SOTD raw data is captured even when the agent doesn't bother.
//
// Graceful-degrade: exits 0 with `skipped:` if fetch fails or markup
// changed.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

const OUT_DIR = '.claude/improvement/sotd';
const GALLERY = 'https://www.awwwards.com/websites/sotd/';
const TIMEOUT_MS = 15000;

function log(...a) {
  console.error('[sotd-compare]', ...a);
}

function shortSha() {
  try {
    return execFileSync('git', ['log', '-1', '--format=%h'], { encoding: 'utf8' }).trim();
  } catch {
    return 'pending';
  }
}

async function fetchWithTimeout(url) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const r = await fetch(url, {
      signal: ctrl.signal,
      headers: {
        'user-agent':
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15',
        accept: 'text/html,application/xhtml+xml',
      },
      redirect: 'follow',
    });
    if (!r.ok) throw new Error('http ' + r.status);
    return await r.text();
  } finally {
    clearTimeout(t);
  }
}

function parseTopEntry(html) {
  // Awwwards SOTD index uses an h2/h3 with the site name and an anchor
  // to the case page. Markup changes occasionally — we read defensively
  // and fall through to "unknown" rather than fail.
  const sites = [];

  // Pass 1 — site-of-the-day cards.
  const cardRe =
    /<a[^>]+href="(\/sites\/[^"]+)"[^>]*>[\s\S]*?<h3[^>]*>([\s\S]*?)<\/h3>(?:[\s\S]*?<span[^>]+by[^>]*>([\s\S]*?)<\/span>)?/gi;
  let m;
  while ((m = cardRe.exec(html))) {
    sites.push({
      url: 'https://www.awwwards.com' + m[1],
      name: m[2].replace(/<[^>]+>/g, '').trim(),
      by: (m[3] || '').replace(/<[^>]+>/g, '').trim(),
    });
    if (sites.length >= 5) break;
  }

  if (!sites.length) {
    // Fallback — sometimes the gallery encodes ld+json with the SOTD.
    const jsonLdRe = /<script[^>]+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi;
    let j;
    while ((j = jsonLdRe.exec(html))) {
      try {
        const obj = JSON.parse(j[1]);
        if (obj?.['@type'] === 'CreativeWork' || obj?.name) {
          sites.push({
            name: obj.name || 'unknown',
            url: obj.url || GALLERY,
            by: obj.author?.name || '',
          });
        }
      } catch {}
    }
  }

  return sites[0] || null;
}

async function main() {
  const sha = shortSha();
  mkdirSync(OUT_DIR, { recursive: true });
  const outPath = `${OUT_DIR}/${sha}.md`;
  if (existsSync(outPath)) {
    console.log(`skipped: ${outPath} already exists`);
    return;
  }

  let html;
  try {
    html = await fetchWithTimeout(GALLERY);
  } catch (e) {
    console.log('skipped: fetch failed —', e.message);
    return;
  }

  const top = parseTopEntry(html);
  if (!top) {
    console.log('skipped: could not parse SOTD entry — gallery markup may have changed');
    return;
  }

  const body = `# SOTD comparison — ${new Date().toISOString().slice(0, 10)} (commit ${sha})

**Today's Awwwards SOTD.** [${top.name}](${top.url})${top.by ? ` — by ${top.by}` : ''}.

This skeleton was auto-generated by \`sotd-compare.mjs\`. The hourly
routine's main agent is invited (but not required) to expand the
three bullets below by inspecting the SOTD page and the just-shipped
BFS change.

## Delta — what they do that we don't

- _(unexpanded — fill at next routine pass)_

## Delta — what we do that they don't

- _(unexpanded)_

## Net jury read

- _(unexpanded — would BFS now hold up next to ${top.name} on Awwwards? Why or why not.)_
`;

  writeFileSync(outPath, body);
  console.log(`sotd: ${top.name} → ${outPath}`);
}

main().catch((e) => {
  console.error('[sotd-compare] unhandled:', e.message);
  process.exit(0);
});
